### ISSUE TITLE
Nvidia Jetson Nano Setup

### ISSUE THREAD

**Issue by robbiebbaker** [UBCAgroBot/AppliedAI#6]
The Nvidia Jetson Nano needs to be set up to run ROS 2 Foxy and support the Intel Realsense D455 camera.

**Hardware**

- Nvidia Jetson Nano
- Intel Realsense D455

**Software**

- Jetpack
- Ubuntu 20.04
- ROS2 Foxy
- Realsense Wrapper

For more information about setting up a Jetson Nano please see this [link](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit)
For more information about installing ROS 2 Foxy on a Jetson please see this[ link](https://github.com/jetsonhacks/installROS2)
For more information about installing the Realsense Wrapper please see this [link](https://github.com/vanderbiltrobotics/realsense-ros)

**Comment by robbiebbaker** [comment]
Dead end. Jetson dead. Will get new Jetson's. In meantime will use Raspberry Pi + Google Coral. Thanks for looking into it!

**Comment by Takunda619** [comment]
Ok no worries. Shame about the Jetson, but thanks for letting me know!
